server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 20000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: DDD-Base-Demo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  cache:
    type: redis
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://daoquanghuy2702:quanghuy2702@cluster0.w30cwhv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:lao_network}
    redis:
      address: ${REDIS_ADDRESS:redis://127.0.0.1:6379}

database:
  jdbcUrl: ${DB_URL:jdbc:mysql://localhost:3306/demo}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:123456}

hikari:
  minimum-idle: 1500
  maximum-pool-size: 30000
  idle-timeout: 30000
  max-lifetime: 1800000
  connection-test-query: SELECT 1
  pool-name: ApiAppHikariPool
  driverClass: org.mariadb.jdbc.Driver

elasticsearch:
  host: huy-search-7190964019.us-east-1.bonsaisearch.net:443
  username: qu7akvysw
  password: vyya6rlbmi
