server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 20000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: DDD-Base-Demo
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/ORCLPDB}
    username: ${DB_USERNAME:hr}
    password: ${DB_PASSWORD:hr}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 1500
      maximum-pool-size: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
      pool-name: ApiAppHikariPool
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  cache:
    type: redis
  data:
    redis:
      address: ${REDIS_ADDRESS:redis://127.0.0.1:6379}

elasticsearch:
  host: huy-search-7190964019.us-east-1.bonsaisearch.net:443
  username: qu7akvysw
  password: vyya6rlbmi

